"""
Report Generator — auto-generate meeting reports and emails.
Uses Jinja2 templates for formatted output.
"""
from datetime import datetime
import re
from jinja2 import Template


# ── Markdown Report Template ──
MARKDOWN_TEMPLATE = Template("""# 📋 Meeting Report: {{ title }}
**Date:** {{ date }}
**Duration:** ~{{ stats.estimated_duration }} minutes | **Words:** {{ stats.word_count | default('N/A') }} | **Speakers:** {{ stats.speaker_count | default('N/A') }}
**Productivity Score:** {{ productivity_score.total }}/100 ({{ productivity_score.grade }} — {{ productivity_score.label }})
**Overall Sentiment:** {{ sentiment.label | capitalize }}

---

## 📝 Executive Summary
{{ short_summary }}

## 📄 Detailed Summary
{{ detailed_summary }}

## 🔑 Key Bullet Points
{% for point in bullet_points %}- {{ point }}
{% endfor %}

---

## ⚖️ Decisions Made
{% if decisions %}{% for d in decisions %}- ✅ {{ d }}
{% endfor %}{% else %}_No formal decisions detected._
{% endif %}

---

## ✅ Action Items

| # | Task | Assignee | Deadline | Priority | Status |
|---|------|----------|----------|----------|--------|
{% for t in tasks %}\
| {{ loop.index }} | {{ t.task[:80] }}{% if t.task|length > 80 %}...{% endif %} | {{ t.assignee }} | {{ t.deadline }} | {{ t.priority | upper }} | {{ t.status }} |
{% endfor %}

---

## ⚠️ Risks & Concerns
{% if risks %}{% for r in risks %}- **[{{ r.severity | upper }}]** {{ r.description }}
{% endfor %}{% else %}_No significant risks detected._
{% endif %}

---

## 👥 Participant Contributions
{% if participants %}{% for p in participants %}\
- **{{ p.name }}**: {{ p.utterance_count }} utterances, {{ p.word_count }} words ({{ p.contribution_pct }}%) — Sentiment: {{ p.sentiment.label }}
{% endfor %}{% else %}_Speaker data not available._
{% endif %}

## 🗂️ Discussion Topics
{% for t in topics %}\
### Topic {{ loop.index }}: {{ t.topic }}
- {{ t.sentences | length }} sentences discussed
- Key sentences: _"{{ t.sentences[0][:120] }}..."_
{% endfor %}

---

## 📊 Productivity Breakdown
- Action Density: {{ productivity_score.breakdown.action_density }}/25
- Decision Ratio: {{ productivity_score.breakdown.decision_ratio }}/25
- Participation Balance: {{ productivity_score.breakdown.participation_balance }}/25
- Risk Awareness: {{ productivity_score.breakdown.risk_awareness }}/15
- Clarity: {{ productivity_score.breakdown.clarity }}/10

---
_Generated by MeetMind AI — {{ generated_at }}_
""")

# ── Email Template ──
EMAIL_TEMPLATE = Template("""Subject: Meeting Follow-Up — {{ title }}

Hi Team,

Here is a brief summary from our meeting "{{ title }}" held on {{ date }}.

**Summary:**
{{ short_summary }}

{% if decisions %}**Key Decisions:**
{% for d in decisions %}- {{ d }}
{% endfor %}{% endif %}

{% if tasks %}**Action Items:**
{% for t in tasks %}- {{ t.task[:100] }} → **{{ t.assignee }}** (Due: {{ t.deadline }}, Priority: {{ t.priority | upper }})
{% endfor %}{% endif %}

{% if risks %}**Risks to Watch:**
{% for r in risks %}- [{{ r.severity | upper }}] {{ r.description[:100] }}
{% endfor %}{% endif %}

Please review the action items assigned to you and confirm your deadlines. Let me know if you have any questions.

Best regards,
MeetMind AI Assistant

---
_Productivity Score: {{ productivity_score.total }}/100 ({{ productivity_score.label }})_
""")

# ── HTML Report Template ──
HTML_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Meeting Report — {{ title }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Inter, Arial, sans-serif; color: #1e293b; line-height: 1.7; padding: 40px; max-width: 900px; margin: auto; background: #fafbfc; }
  h1 { color: #6d28d9; font-size: 28px; margin-bottom: 8px; }
  h2 { color: #7c3aed; font-size: 20px; margin-top: 30px; margin-bottom: 12px; border-bottom: 2px solid #ede9fe; padding-bottom: 6px; }
  h3 { color: #475569; font-size: 16px; margin-top: 16px; }
  p, li { margin-bottom: 8px; }
  .meta { color: #64748b; font-size: 14px; margin-bottom: 20px; }
  .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 13px; font-weight: 600; margin: 2px; }
  .badge-high { background: #fee2e2; color: #dc2626; }
  .badge-medium { background: #fef3c7; color: #d97706; }
  .badge-low { background: #d1fae5; color: #065f46; }
  .badge-score { background: #ede9fe; color: #6d28d9; font-size: 16px; }
  table { width: 100%%; border-collapse: collapse; margin: 16px 0; }
  th, td { padding: 10px 14px; text-align: left; border-bottom: 1px solid #e2e8f0; }
  th { background: #f1f5f9; font-weight: 600; color: #475569; }
  .section { margin-bottom: 28px; }
  .footer { text-align: center; color: #94a3b8; font-size: 12px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; }
</style>
</head>
<body>
<h1>📋 {{ title }}</h1>
<p class="meta">{{ date }} · ~{{ stats.estimated_duration }} min · {{ stats.word_count }} words · {{ stats.speaker_count }} speakers
<span class="badge badge-score">{{ productivity_score.total }}/100 {{ productivity_score.grade }}</span></p>

<div class="section">
<h2>📝 Summary</h2>
<p>{{ short_summary }}</p>
<p style="color:#64748b;margin-top:12px">{{ detailed_summary }}</p>
</div>

<div class="section">
<h2>⚖️ Decisions</h2>
<ul>{% for d in decisions %}<li>{{ d }}</li>{% endfor %}</ul>
{% if not decisions %}<p style="color:#94a3b8">No decisions detected.</p>{% endif %}
</div>

<div class="section">
<h2>✅ Action Items</h2>
<table>
<thead><tr><th>#</th><th>Task</th><th>Assignee</th><th>Deadline</th><th>Priority</th></tr></thead>
<tbody>
{% for t in tasks %}
<tr>
<td>{{ loop.index }}</td>
<td>{{ t.task[:80] }}{% if t.task|length > 80 %}...{% endif %}</td>
<td>{{ t.assignee }}</td>
<td>{{ t.deadline }}</td>
<td><span class="badge badge-{{ t.priority }}">{{ t.priority | upper }}</span></td>
</tr>
{% endfor %}
</tbody></table>
</div>

{% if risks %}
<div class="section">
<h2>⚠️ Risks</h2>
<ul>{% for r in risks %}<li><span class="badge badge-{{ r.severity }}">{{ r.severity | upper }}</span> {{ r.description }}</li>{% endfor %}</ul>
</div>
{% endif %}

{% if participants %}
<div class="section">
<h2>👥 Participants</h2>
<table>
<thead><tr><th>Name</th><th>Utterances</th><th>Words</th><th>Contribution</th><th>Sentiment</th></tr></thead>
<tbody>
{% for p in participants %}
<tr><td><strong>{{ p.name }}</strong></td><td>{{ p.utterance_count }}</td><td>{{ p.word_count }}</td><td>{{ p.contribution_pct }}%</td><td>{{ p.sentiment.label }}</td></tr>
{% endfor %}
</tbody></table>
</div>
{% endif %}

<div class="footer">Generated by MeetMind AI · {{ generated_at }}</div>
</body></html>
""")


class ReportGenerator:
    """Generate formatted reports from meeting analysis."""

    @staticmethod
    def generate_ics(analysis: dict, title: str = "Meeting") -> str:
        """Generate an iCalendar file containing one all-day event per task."""
        meeting_date = ReportGenerator._parse_calendar_date(
            analysis.get("timestamp", datetime.now().isoformat()), datetime.now()
        )
        events = []
        for index, task in enumerate(analysis.get("tasks", [])):
            deadline = str(task.get("deadline", "Not specified"))
            due_date = ReportGenerator._parse_calendar_date(deadline, meeting_date)
            end_date = due_date.replace(hour=0, minute=0, second=0, microsecond=0)
            end_date = end_date.fromordinal(end_date.toordinal() + 1)
            summary = f"[{task.get('priority', 'low')}] {task.get('task', 'Action item')}"
            description = (
                f"Assignee: {task.get('assignee', 'Not specified')}\n"
                f"Deadline: {deadline}\nSource meeting: {title}"
            )
            events.extend([
                "BEGIN:VEVENT",
                f"UID:meetmind-{index}-{int(datetime.now().timestamp())}@meetmind",
                f"DTSTAMP:{datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')}",
                f"DTSTART;VALUE=DATE:{due_date.strftime('%Y%m%d')}",
                f"DTEND;VALUE=DATE:{end_date.strftime('%Y%m%d')}",
                f"SUMMARY:{ReportGenerator._ics_escape(summary)}",
                f"DESCRIPTION:{ReportGenerator._ics_escape(description)}",
                "END:VEVENT",
            ])
        return "\r\n".join([
            "BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//MeetMind//Meeting Actions//EN",
            "CALSCALE:GREGORIAN", *events, "END:VCALENDAR", ""
        ])

    @staticmethod
    def _parse_calendar_date(value: str, fallback: datetime) -> datetime:
        """Parse common ISO, numeric, and month-name deadline formats."""
        text = str(value or "").strip()
        for date_format in ("%Y-%m-%d", "%Y/%m/%d", "%B %d, %Y", "%b %d, %Y", "%B %d", "%b %d"):
            try:
                parsed = datetime.strptime(text, date_format)
                return parsed.replace(year=fallback.year) if "%Y" not in date_format else parsed
            except ValueError:
                continue
        match = re.search(r"\b(\d{1,2})[/. -](\d{1,2})(?:[/. -](\d{2,4}))?\b", text)
        if match:
            year = int(match.group(3) or fallback.year)
            if year < 100:
                year += 2000
            try:
                return datetime(year, int(match.group(2)), int(match.group(1)))
            except ValueError:
                pass
        return fallback

    @staticmethod
    def _ics_escape(value: str) -> str:
        return str(value).replace("\\", "\\\\").replace(";", "\\;").replace(",", "\\,").replace("\n", "\\n")

    @staticmethod
    def generate_markdown(analysis: dict, title: str = "Meeting") -> str:
        """Generate a Markdown report."""
        context = ReportGenerator._build_context(analysis, title)
        return MARKDOWN_TEMPLATE.render(**context)

    @staticmethod
    def generate_email(analysis: dict, title: str = "Meeting") -> str:
        """Generate an email-style report."""
        context = ReportGenerator._build_context(analysis, title)
        return EMAIL_TEMPLATE.render(**context)

    @staticmethod
    def generate_html(analysis: dict, title: str = "Meeting") -> str:
        """Generate an HTML report."""
        context = ReportGenerator._build_context(analysis, title)
        return HTML_TEMPLATE.render(**context)

    @staticmethod
    def _build_context(analysis: dict, title: str) -> dict:
        """Prepare template context from analysis data."""
        timestamp = analysis.get("timestamp", datetime.now().isoformat())
        try:
            date = datetime.fromisoformat(timestamp).strftime("%B %d, %Y at %I:%M %p")
        except (ValueError, TypeError):
            date = timestamp

        return {
            "title": title,
            "date": date,
            "short_summary": analysis.get("short_summary", "No summary available."),
            "detailed_summary": analysis.get("detailed_summary", ""),
            "bullet_points": analysis.get("bullet_points", []),
            "decisions": analysis.get("decisions", []),
            "tasks": analysis.get("tasks", []),
            "topics": analysis.get("topics", []),
            "risks": analysis.get("risks", []),
            "participants": analysis.get("participants", []),
            "sentiment": analysis.get("sentiment", {"label": "neutral"}),
            "stats": analysis.get("stats", {}),
            "productivity_score": analysis.get("productivity_score", {"total": 0, "grade": "N/A", "label": "N/A", "breakdown": {}}),
            "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        }
